namespace: ekwest93
name: my_own_collection
version: 1.0.0
readme: README.md
authors:
  - Your Name
description: My custom module for file creation
license:
  - MIT
tags:
  - files
repository: https://github.com/ekwest93/my_own_collection
