namespace: ekwest93
name: my_own_collection
version: 1.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>
description: My custom Ansible collection
license:
  - MIT
tags:
  - custom
repository: https://github.com/ekwest93/my_own_collection
documentation: https://github.com/ekwest93/my_own_collection
homepage: https://github.com/ekwest93/my_own_collection
issues: https://github.com/ekwest93/my_own_collection/issues
build_ignore:
  - .gitignore
  - .github
  - tests/output
  - venv
