---
- name: Test module
  hosts: localhost
  connection: local
  tasks:
    - name: Create file
      my_own_module:
        path: /tmp/test.txt
        content: "Hello"
      register: result
    - debug: var=result
