---
- name: Test my role
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: my_file_role
      vars:
        my_module_path: /tmp/role_file.txt
        my_module_content: "Created by role from collection!"
